  //// Constantes de la blockchain
const BLOCKCHAIN_CONSTANTS = {
    SMARTCONTRACT_BUY_PRODUCT : "SC_BUY_PRODUCT",
    SMARTCONTRACT_BUY_TERRAIN : "SC_BUY_TERRAIN",
    SMARTCONTRACT_BUY_ITEM : "SC_BUY_ITEM",
    SMARTCONTRACT_PLANT : "SC_PLANT",
    SMARTCONTRACT_BUILD : "SC_BUILD",

}

 //// Constantes del juego
const GAME_CONSTANS= {

    // ESTADO PARTIDA
    GAME_STATUS_PLAYING : "GAME_PLAYING",
    GAME_STATUS_ENDED : "GAME_ENDED",
    
    // TERRENOS
    TERRAIN_STATUS_EMPTY : "TERRAIN_EMPTY",
    TERRAIN_STATUS_PLANTED : "TERRAIN_PLANTED",
    TERRAIN_STATUS_CONSTUCTED : "TERRAIN_CONSTUCTED",

    //PRODUCTOS
    PRODUCT_STATUS_SEED : "PRODUCT_SEED",
    PRODUCT_STATUS_PLANTED : "PRODUCT_PLANTED",
    PRODUCT_STATUS_GROW : "PRODUCT_GROW",
    PRODUCT_STATUS_ROTTEN : "PRODUCT_ROTTEN",
    PRODUCT_STATUS_DRY : "PRODUCT_DRY",

    //CONSTRUCCIONES
    BUILDING_STATUS_BUILD : "BUILDING_PROCESSING",
    BUILDING_STATIS_COMPLETED : "BUILDING_COMPLETED"
}


module.exports = {
    BLOCKCHAIN_CONSTANTS,
    GAME_CONSTANS
}