  //// Constantes de la blockchain
const BLOCKCHAIN_CONSTANTS = {
    SMARTCONTRACT_BUY_PRODUCT : "SC_BUY_PRODUCT",
    SMARTCONTRACT_BUY_TERRAIN : "SC_BUY_TERRAIN",
    SMARTCONTRACT_BUY_ITEM : "SC_BUY_ITEM",
    SMARTCONTRACT_PLANT : "SC_PLANT",
    SMARTCONTRACT_BUILD : "SC_BUILD",
}

 //// Constantes del juego
const GAME_CONSTANS= {
    // ESTADO PARTIDA
    GAME_STATUS_PLAYING : "GAME_PLAYING",
    GAME_STATUS_ENDED : "GAME_ENDED",
    // TERRENOS
    TERRAIN_STATUS_EMPTY : "TERRAIN_EMPTY",
    TERRAIN_STATUS_PLANTED : "TERRAIN_PLANTED",
    TERRAIN_STATUS_CONSTUCTED : "TERRAIN_CONSTUCTED",
    //PRODUCTOS
    PRODUCT_STATUS_SEED : "PRODUCT_SEED",
    PRODUCT_STATUS_PLANTED : "PRODUCT_PLANTED",
    PRODUCT_STATUS_GROW : "PRODUCT_GROW",
    PRODUCT_STATUS_ROTTEN : "PRODUCT_ROTTEN",
    PRODUCT_STATUS_DRY : "PRODUCT_DRY",
    //CONSTRUCCIONES
    BUILDING_STATUS_BUILD : "BUILDING_PROCESSING",
    BUILDING_STATIS_COMPLETED : "BUILDING_COMPLETED",

    //EVENTOS
    EVENT_PLAYER_EXIT : "PLAYER_EXIT",

    //ACCIONES 
    ACTION_TERRAIN_BUILD : "TERRAIN_BUILD",
    ACTION_TERRAIN_PLANT : "TERRAIN_PLANT",

    ACTION_PLANT_RECOLLECT : "PLANT_RECOLLECT",
    ACTION_PLANT_WATTER : "PLANT_WATTER",

    ACTION_PLAYER_END_TURN: "PLAYER_END_TURN",
}

const ROOM_CONSTANTS = {
    //ESTADO
    STATUS_EMPTY : "EMPTY",
    STATUS_WAITING: "WAITING",
    STATUS_RUNNING: "RUNNING",
    //TIPO
    TYPE_PUBLIC : "PUBLIC",
    TYPE_PRIVATE : "PRIVATE",
    //EVENTOS
    EVENT_PLAYERMESSAGE : "PLAYER_MESSAGE",
    EVENT_PLAYER_JOIN : "PLAYER_JOIN",
    EVENT_PLAYER_EXIT : "PLAYER_EXIT",
    EVENT_PLAYER_CHANGE_STATUS : "PLAYER_CHANGE_STATUS",
    EVENT_GAME_START : "GAME_START"
}

module.exports = {
    BLOCKCHAIN_CONSTANTS,
    GAME_CONSTANS,
    ROOM_CONSTANTS
}